config/routes.rb
Rails.application.routes.draw do
  resources :flights, only: [ :index, :show ] do
    resources :bookings, only: [ :index, :show, :new, :create, :destroy ]
  end
  resources :airports, only: [ :index ]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "flights#index"
end

app/models/airport.rb
class Airport < ApplicationRecord
  # validations
  validates :airport_code,
    length: { is: 3 },
    presence: true,
    uniqueness: true,
    format: { with: /\A[A-Z]+\z/, message: "only allows capital letters" }

  # associations
  has_many :departing_flights,
    foreign_key: "departure_airport_id",
    class_name: "Flight"
  has_many :arriving_flights,
    foreign_key: "arrival_airport_id",
    class_name: "Flights"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  # associations
  belongs_to :flight
  has_many :passengers, inverse_of: :booking
  accepts_nested_attributes_for :passengers, allow_destroy: true
end

app/models/flight.rb
class Flight < ApplicationRecord
  # associations
  belongs_to :departure_airport, class_name: "Airport"
  belongs_to :arrival_airport, class_name: "Airport"
  has_many :bookings

  # validations
  validates :departure_datetime, presence: true
  validates :arrival_datetime, presence: true, comparison: { greater_than: :departure_datetime }
  validates :departure_airport_id, presence: true
  validates :arrival_airport_id, presence: true, comparison: { other_than: :departure_airport_id }
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  # associations
  belongs_to :booking
end

app/controllers/airports_controller.rb
class AirportsController < ApplicationController
  before_action :set_airport, only: %i[ show edit update destroy ]

  # GET /airports or /airports.json
  def index
    @airports = Airport.all
  end

  # GET /airports/1 or /airports/1.json
  def show
  end

  # GET /airports/new
  def new
    @airport = Airport.new
  end

  # GET /airports/1/edit
  def edit
  end

  # POST /airports or /airports.json
  def create
    @airport = Airport.new(airport_params)

    respond_to do |format|
      if @airport.save
        format.html { redirect_to @airport, notice: "Airport was successfully created." }
        format.json { render :show, status: :created, location: @airport }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @airport.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /airports/1 or /airports/1.json
  def update
    respond_to do |format|
      if @airport.update(airport_params)
        format.html { redirect_to @airport, notice: "Airport was successfully updated." }
        format.json { render :show, status: :ok, location: @airport }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @airport.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /airports/1 or /airports/1.json
  def destroy
    @airport.destroy!

    respond_to do |format|
      format.html { redirect_to airports_path, status: :see_other, notice: "Airport was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_airport
      @airport = Airport.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def airport_params
      params.expect(airport: [ :airport_code ])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_flight
  before_action :set_booking, only: %i[ show destroy ]


  def index
    @bookings = @flight.bookings
  end

  def show
  end

  def new
    @booking = @flight.bookings.build

    @passenger_count = params.expect(:passenger_count).to_i
    @passenger_count.times { @booking.passengers.build }
  end

  def create
    @booking = @flight.bookings.build(booking_params)

    if @booking.save
      redirect_to flight_booking_path(@flight, @booking), notice: "Booking was successfully created."
    else
      render :new
    end
  end

  # DELETE /bookings/1 or /bookings/1.json
  def destroy
    @booking.destroy!

    respond_to do |format|
      format.html { redirect_to flights_path, status: :see_other, notice: "Booking was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def booking_params
      params.expect(booking: [ passengers_attributes: [ [ :name, :email ] ] ])
    end

    def set_flight
      @flight = Flight.find(params.expect(:flight_id))
    end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  before_action :set_flight, only: %i[ show ]

  # GET /flights or /flights.json
  def index
    if params.include? :flight_id
      @flight = Flight.find(params.expect(:flight_id))
      redirect_to new_flight_booking_path(
        @flight,
        passenger_count: params.expect(:passenger_count)
      )
    end

    search_params = [ :departure_datetime, :arrival_airport_id, :departure_airport_id ]
    if search_params.all? { |key| params.include? key }
      @flights = Flight.where(
        "departure_airport_id = ? AND arrival_airport_id = ? AND DATE(departure_datetime) = ?",
        params.expect(:departure_airport_id),
        params.expect(:arrival_airport_id),
        params.expect(:departure_datetime)
      )
      @passenger_count = params.expect(:passenger_count)
    else
      @flights = nil
    end
  end

  # GET /flights/1 or /flights/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flight
      @flight = Flight.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def flight_params
      params.expect(flight: [ :departure_datetime, :arrival_datetime, :departure_airport_id, :arrival_airport_id ])
    end
end

app/helpers/airports_helper.rb
module AirportsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/passengers_helper.rb
module PassengersHelper
end

app/views/airports/_airport.html.erb
<div id="<%= dom_id airport %>">
  <p>
    <strong>Airport code:</strong>
    <%= airport.airport_code %>
  </p>

</div>

app/views/airports/_form.html.erb
<%= form_with(model: airport) do |form| %>
  <% if airport.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(airport.errors.count, "error") %> prohibited this airport from being saved:</h2>

      <ul>
        <% airport.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :airport_code, style: "display: block" %>
    <%= form.text_field :airport_code %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/airports/edit.html.erb
<% content_for :title, "Editing airport" %>

<h1>Editing airport</h1>

<%= render "form", airport: @airport %>

<br>

<div>
  <%= link_to "Show this airport", @airport %> |
  <%= link_to "Back to airports", airports_path %>
</div>

app/views/airports/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Airports" %>

<h1>Airports</h1>

<div id="airports">
  <% @airports.each do |airport| %>
    <%= render airport %>
    <%# <p> %>
      <%#= link_to "Show this airport", airport %>
    <%# </p> %>
  <% end %>
</div>

<%#= link_to "New airport", new_airport_path %>

app/views/airports/new.html.erb
<% content_for :title, "New airport" %>

<h1>New airport</h1>

<%= render "form", airport: @airport %>

<br>

<div>
  <%= link_to "Back to airports", airports_path %>
</div>

app/views/airports/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @airport %>

<div>
  <%= link_to "Edit this airport", edit_airport_path(@airport) %> |
  <%= link_to "Back to airports", airports_path %>

  <%= button_to "Destroy this airport", @airport, method: :delete %>
</div>

app/views/bookings/_booking.html.erb
<div id="<%= dom_id booking %>">
  <%= render "flights/flight", flight: @flight %>

  <% booking.passengers.each_with_index do |passenger, index| %>
    <h3>Passenger <%= index+1%></h3>
    <%= render "passengers/passenger", passenger: passenger %>
  <% end %>

  

</div>

app/views/bookings/_form.html.erb
<%= form_with(model: booking, url: flight_bookings_path(@flight)) do |form| %>
  <% if booking.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
        <% booking.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <ul>
    <%= form.fields_for :passengers do |passenger_form| %>
      <li>
        <h3>Passenger details:</h3>
        <%= passenger_form.label :name, style: "display: block" %>
        <%= passenger_form.text_field :name %>

        <%= passenger_form.label :email, style: "display: block" %>
        <%= passenger_form.text_field :email %>
      </li>
    <% end %>
  </ul>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/bookings/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Bookings" %>

<h1>Bookings</h1>

<div id="bookings">
  <% @bookings.each do |booking| %>
    <%= render booking %>
    <p>
      <%= link_to "Show this booking", flight_booking_path(@flight, booking) %>
    </p>
  <% end %>
</div>

<%#= link_to "New booking", new_booking_path %>

app/views/bookings/new.html.erb
<% content_for :title, "New booking" %>

<h1>New booking</h1>

<%= render "flights/flight", flight: @flight %>

<%= render "form", booking: @booking %>

<br>

<div>
  <%#= link_to "Back to bookings", bookings_path %>
</div>

app/views/bookings/show.html.erb
<div><%= link_to "Back to bookings", flight_bookings_path(@flight) %></div>

<p style="color: green"><%= notice %></p>

<h1>Booking details</h1>

<%= render @booking %>

<div>
  <%#= link_to "Edit this booking", edit_flight_booking_path(@flight, @booking) %>
  <%= button_to "Destroy this booking", flight_booking_path(@flight, @booking), method: :delete %>
</div>

app/views/flights/_flight.html.erb
<div id="<%= dom_id flight %>">
  <p>
    <strong>From:</strong>
    <%= flight.departure_airport.airport_code %>
  </p>
  
  <p>
    <strong>To:</strong>
    <%= flight.arrival_airport.airport_code %>
  </p>
  
  <p>
    <strong>Departs:</strong>
    <%= flight.departure_datetime %>
  </p>

  <p>
    <strong>Journey duration:</strong>
    <%= ((flight.arrival_datetime - flight.departure_datetime)/60/60).round(1) %>
    hours
  </p>

  <p>
    <strong>Arrives:</strong>
    <%= flight.arrival_datetime %>
  </p>
  
</div>

app/views/flights/_form.html.erb
<%= form_with(model: flight) do |form| %>
  <% if flight.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(flight.errors.count, "error") %> prohibited this flight from being saved:</h2>

      <ul>
        <% flight.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :flight_departure_airport_id, "From", style: "display: block" %>
    <%= form.collection_select :departure_airport_id, Airport.order(:airport_code), :id, :airport_code %>
  </div>

  <div>
    <%= form.label :flight_arrival_airport_id, "To", style: "display: block" %>
    <%= form.collection_select :arrival_airport_id, Airport.order(:airport_code), :id, :airport_code %>
  </div>

  <div>
    <%= form.label :departure_datetime, "Departs", style: "display: block" %>
    <%= form.datetime_field :departure_datetime %>
  </div>

  <div>
    <%= form.label :arrival_datetime, "Arrives", style: "display: block" %>
    <%= form.datetime_field :arrival_datetime %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/flights/_search_flights.html.erb
<%= form_with url: flights_path, method: :get do |form| %>
  <div>
    <%= form.label :departure_airport_id, "From:", style: "display: block" %>
    <%= form.collection_select :departure_airport_id, Airport.order(:airport_code), :id, :airport_code, required: true %>
  </div>

  <div>
    <%= form.label :arrival_airport_id, "To:", style: "display: block" %>
    <%= form.collection_select :arrival_airport_id, Airport.order(:airport_code), :id, :airport_code , required: true%>
  </div>

  <div>
    <%= form.label :departure_datetime, "Departs:", style: "display: block" %>
    <%= form.date_field :departure_datetime, required: true %>
  </div>

  <div>
    <%= form.label :passenger_count, "Travelers:", style: "display: block" %>
    <%= form.select :passenger_count, (1..5) %>
  </div>

  <%= form.submit "Search" %>
<% end %>

app/views/flights/_select_flight.html.erb
<h3>Select flight to proceed:</h3>

<%= form_with url: flights_path, method: :get do |form|%>

  <% @flights.each do |flight| %>
    <div>
      <%= render flight %>
      <%#= link_to "Select this flight", flight %>
      <%= form.radio_button :flight_id, flight.id %>
    </div>
  <% end %>

  <div>
    <%= form.hidden_field :passenger_count, value: @passenger_count %>
  </div>

  <div>
    <%= form.submit "Next" %>
  </div>

<% end %>

app/views/flights/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Flights" %>

<h1>Search flights:</h1>

<div>
  <%= render "search_flights" %>
</div>

<div><%= link_to "Clear", flights_path %></div>

<div id="flights">
  <% if @flights.nil? %>
    <p>Search for flights</p>
  <% elsif @flights.empty? %>
    <p>No flights found for your destination on given date!</p>
  <% else %>
    <%= render "select_flight" %>
  <% end %>
</div>

<%#= link_to "New flight", new_flight_path %>

app/views/flights/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @flight %>

<div>
  <%#= link_to "Edit this flight", edit_flight_path(@flight) %>
  <%= link_to "Back to flights", flights_path %>

  <%#= button_to "Destroy this flight", @flight, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Odin Flight Booker" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/passengers/_form.html.erb
<%= form_with(model: passenger) do |form| %>
  <% if passenger.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(passenger.errors.count, "error") %> prohibited this passenger from being saved:</h2>

      <ul>
        <% passenger.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/passengers/_passenger.html.erb
<div id="<%= dom_id passenger %>">
  <p>
    <strong>Name:</strong>
    <%= passenger.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= passenger.email %>
  </p>

</div>